apiVersion: apps/v1
kind: Deployment
metadata:
  name: javaapp
spec:
  replicas: 2
  
  selector:
    matchLabels:
      app: javaapp
  template:
    metadata:
      labels:
        app: javaapp
    spec:
      containers:
      - name: javaappcontainer
        image: nileshyav/java_ready_image:latest39
        ports:
        - containerPort: 8080
         
