apiVersion: v1
kind: Service
metadata:
  name: javaappservice
  labels: 
    name: java-service
spec:
  type: NodePort
  selector:
    app: javaapp
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30004